"""initial migration

Revision ID: 7be0415ea089
Revises: None
Create Date: 2016-04-24 18:34:39.786570

"""

# revision identifiers, used by Alembic.
revision = '7be0415ea089'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test1')
    op.drop_table('test2')
    op.drop_table('test3')
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'comments', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['followed_id'], ['id'])
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.create_index(op.f('ix_roles_flag'), 'roles', ['flag'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.drop_index('name', table_name='roles')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.drop_index('email', table_name='users')
    op.drop_index('name', table_name='users')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index('name', 'users', ['name'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('name', 'roles', ['name'], unique=True)
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_flag'), table_name='roles')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.create_table('test3',
    sa.Column('name', mysql.CHAR(length=20), nullable=True),
    mysql_default_charset=u'gbk',
    mysql_engine=u'InnoDB'
    )
    op.create_table('test2',
    sa.Column('name', mysql.CHAR(length=20), nullable=True),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('test1',
    sa.Column('name', mysql.CHAR(length=20), nullable=True),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
